name: facetracker # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Bitrix24 face tracker # 79 char long summary
description: |
  This app can detect faces and send it to Bitrix24,
  so if client will come again we can detect it and link to previos visit.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./icon.png
apps:
  facetracker:
    command: java -jar ${SNAP}/facetracker.jar
    environment:
      JAVA_HOME: $SNAP
    daemon: simple
    plugs: [network, network-bind]

parts:
  facetracker-jar:
    plugin: dump
    source: ./bin/
    after: [jdk-dump]
  jdk-dump:
    plugin: dump
#    source: ../jdk-8u144-linux-arm64-vfp-hflt.tar.gz
    source: https://bitbucket.org/firstopensystems/facetracker-jar/downloads/jdk-8u144-linux-arm64-vfp-hflt.tar.gz
#  opencv-snap:
#    plugin: cmake
#    source: https://github.com/opencv/opencv/archive/3.3.0.tar.gz
#    configflags: 
#      - -DCMAKE_BUILD_TYPE=RELEASE
#      - -DCMAKE_INSTALL_PREFIX=/usr
#      - -DBUILD_SHARED_LIBS=OFF
#      - -DWITH_CUDA=OFF
#      - -DOPENCV_EXTRA_MODULES_PATH=../../opencv-contrib-snap/src/modules      
#    after: [opencv-contrib-snap]
#    build-packages:
#      - libjpeg-dev
#      - libtiff5-dev
#      - libjasper-dev
#      - libpng12-dev
#      - libavcodec-dev
#      - libavformat-dev
#      - libswscale-dev
#      - libv4l-dev
#      - libxvidcore-dev
#      - libx264-dev
#      - libatlas-base-dev
#    stage-packages:
#      - gfortran
#      - ant
#      - default-jdk
#  opencv-contrib-snap:
#    source: https://github.com/opencv/opencv_contrib/archive/3.3.0.tar.gz
#    plugin: dump
